### ISSUE TITLE
nil pointer dereference on attempt to execute query in case DB is missing

### ISSUE THREAD

**Issue by MaXal** [go-faster/ch#91] opened 2022-04-27 14:21 UTC
```
(*Client).Do.func4\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/query.go:628\n  - UNKNOWN_DATABASE (81): DB::Exception: Database ij doesn't exist"}
{"level":"error","msg":"cannot handle http request","error":"packet: uvarint: read: read: read tcp 127.0.0.1:61219->127.0.0.1:9000: read: connection reset by peer","errorVerbose":"packet:\n    github.com/go-faster/ch.(*Client).Do.func4\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/query.go:609\n  - uvarint:\n    github.com/go-faster/ch.(*Client).packet\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/client.go:214\n  - read:\n    github.com/go-faster/ch/proto.(*Reader).UVarInt\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/proto/reader.go:92\n  - read:\n    github.com/go-faster/ch/proto.(*Reader).ReadFull\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/proto/reader.go:66\n  - read tcp 127.0.0.1:61219->127.0.0.1:9000: read: connection reset by peer"}
{"level":"error","msg":"cannot handle http request","error":"handle packet: UNKNOWN_DATABASE (81): DB::Exception: Database ij doesn't exist","errorVerbose":"handle packet:\n    github.com/go-faster/ch.(*Client).Do.func4\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/query.go:628\n  - UNKNOWN_DATABASE (81): DB::Exception: Database ij doesn't exist"}
{"level":"error","msg":"cannot handle http request","error":"packet: uvarint: read: read: read tcp 127.0.0.1:61220->127.0.0.1:9000: read: connection reset by peer","errorVerbose":"packet:\n    github.com/go-faster/ch.(*Client).Do.func4\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/query.go:609\n  - uvarint:\n    github.com/go-faster/ch.(*Client).packet\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/client.go:214\n  - read:\n    github.com/go-faster/ch/proto.(*Reader).UVarInt\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/proto/reader.go:92\n  - read:\n    github.com/go-faster/ch/proto.(*Reader).ReadFull\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/proto/reader.go:66\n  - read tcp 127.0.0.1:61220->127.0.0.1:9000: read: connection reset by peer"}
{"level":"error","msg":"cannot handle http request","error":"handle packet: UNKNOWN_DATABASE (81): DB::Exception: Database ij doesn't exist","errorVerbose":"handle packet:\n    github.com/go-faster/ch.(*Client).Do.func4\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/query.go:628\n  - UNKNOWN_DATABASE (81): DB::Exception: Database ij doesn't exist"}
{"level":"error","msg":"cannot handle http request","error":"handle packet: UNKNOWN_DATABASE (81): DB::Exception: Database ij doesn't exist","errorVerbose":"handle packet:\n    github.com/go-faster/ch.(*Client).Do.func4\n        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/query.go:628\n  - UNKNOWN_DATABASE (81): DB::Exception: Database ij doesn't exist"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102b3bec8]

goroutine 54 [running]:
github.com/go-faster/ch.(*Client).sendQuery(0x140000b6000, {_, _}, {{0x14000380000, 0x1a8}, {0x140025322d0, 0x24}, {0x0, 0x0}, {0x0, ...}, ...})
        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/query.go:90 +0x228
github.com/go-faster/ch.(*Client).Do.func3()
        /Users/maxim.kolmakov/go/pkg/mod/github.com/go-faster/ch@v0.29.1/query.go:568 +0x7c
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/maxim.kolmakov/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x88
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/maxim.kolmakov/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0xc0
```

**Comment by ernado** [comment] 2022-04-28 12:07
@MaXal are there any concurrent `Do` invocations?

I've added specific test case for "Do on missing db":
https://github.com/go-faster/ch/blob/8139cadff8deef5c1b11302809ff3c175cdd991a/client_test.go#L54-L67

It should work. I think that nil pointer dereference can be caused by concurrent access (i.e. data race), but not sure.

**Comment by ernado** [comment] 2022-04-28 13:14
Please try `v0.30.0` with possible mitigation:

```console
go get github.com/go-faster/ch@v0.30.0
```

Should return error if client connection is already closed.

Also please try running your software with `-race` flag after it and reproducing this condition, I expect some kind of data race.

**Comment by ernado** [comment] 2022-04-29 19:01
Great, I'm closing this issue for now, thank you!

**Closed by ernado** 2022-04-29 19:01 UTC
Labels: bug
